name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-black
        pip install pylint
        pip install mypy
        pip install httpx
        pip install marshmallow
        pip install marshmallow-dataclass
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 victor_smart_kill
    - name: Analysing the code with pylint
      run: |
        pylint --versions
        pylint victor_smart_kill
    - name: Analysing the code with mypy
      run: |
        mypy -p victor_smart_kill 
